apiVersion: v1
kind: Service
metadata:
  name: {{ include "FIAP.Diner.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "FIAP.Diner.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.livenessProbe.httpGet.path }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "FIAP.Diner.selectorLabels" . | nindent 4 }}
