{{ with .Values.postgres }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  type: {{ .portType }}
  ports:
    - port: {{ .port }}
  selector:
    app: {{ .name }}
{{- end }}