# Default values for FIAP.Diner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: cdvt/iburguer
  pullPolicy: IfNotPresent
  tag: latest

nameOverride: ""
fullnameOverride: ""
namespace: iburguer

podLabels: {}

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: "diner-ingress"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: "4.156.123.183"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 500m
    memory: 800Mi
  requests:
    cpu: 100m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /hc
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 5
readinessProbe:
  httpGet:
    path: /hc
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

configmap:
  connectionstring: 
    connection: Host=postgres:5432;Database=iburguer;Username=iburguer;Password=
    password: "1234"

postgres:
  namespace: iburguer
  name: postgres
  image:
    repository: postgres
    tag: 11
  port: 5432
  portType: ClusterIP
  env:
    user:
      key: POSTGRES_USER
      value: iburguer
    password:
      key: POSTGRES_PASSWORD
      value: '1234'
    pgdata:
      key: PGDATA
      value: /var/lib/postgresql/data/pgdata
  volumes: 
    storage:
      namespace: iburguer
      path: /var/lib/postgresql/data
      name: postgres-pv-storage
      volume:
        name: postgres-pv-volume
        spec: 
          capacity:
            storage: 5Gi
          hostPath: "/mnt/data"
      claim:
        name: postgres-pv-claim
        spec:
          resources:
            requests:
              storage: 1Gi
    initdb:
      path: /docker-entrypoint-initdb.d
      name: postgres-pv-initdb
      volume:
        name: postgres-initdb-pv-volume
        spec: 
          capacity:
            storage: 1Mi
          hostPath: 'C:\Users\Matheus Antonio\source\repos\tech-challenge-fiap\FIAP\docker-entrypoint-initdb.d'
      claim:
        name: postgres-initdb-pv-claim
        spec:
          resources:
            requests:
              storage: 1Mi