name: Continuous Integration - iBurguer

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  IMAGE_NAME: iburguer
  ROOT_PROJECT_DIRECTORY: FIAP
  PROJECT_NAME: FIAP.Diner.API
  TEST_PROJECT_NAME: FIAP.Diner.Tests

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Restore dependencies
        run: dotnet restore FIAP/FIAP.Diner.API/FIAP.Diner.API.csproj

      - name: Build
        run: dotnet build FIAP/FIAP.Diner.API/FIAP.Diner.API.csproj

      - name: Test
        run: dotnet test FIAP/FIAP.Diner.Tests/FIAP.Diner.Tests.csproj

  trigger_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger CI/CD Workflow
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/FIAP-G04/iburguer-api/dispatches \
            -d '{"event_type":"api_test"}'