name: Continuous Integration - iBurguer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  IMAGE_NAME: iburguer
  ROOT_PROJECT_DIRECTORY: FIAP
  PROJECT_NAME: FIAP.Diner.API
  TEST_PROJECT_NAME: FIAP.Diner.Tests
  
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    environment: 
      name: Iburguer

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Restore Dependencies
      run: dotnet restore ${{ env.ROOT_PROJECT_DIRECTORY}}/${{ env.PROJECT_NAME}}

    - name: Build Application
      run: dotnet build ${{ env.ROOT_PROJECT_DIRECTORY}}/${{ env.PROJECT_NAME}} --no-restore --configuration Release

    - name: Run Tests
      run: dotnet test ${{ env.ROOT_PROJECT_DIRECTORY}}/${{ env.TEST_PROJECT_NAME}}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Get next version
      uses: reecetech/version-increment@2023.9.3
      id: version
      with:
        scheme: semver
        increment: patch

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}" ${{ env.ROOT_PROJECT_DIRECTORY}} --file ${{ env.ROOT_PROJECT_DIRECTORY}}/${{ env.PROJECT_NAME}}/Dockerfile
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}"
      env:
        DOCKER_BUILDKIT: 1
